---
roles: []

collections:
  - name: community.docker
    version: ">=4.3.0,<5.0"
    source: https://galaxy.ansible.com

  - name: community.general
    version: ">=10.3.0,<11.0"
    source: https://galaxy.ansible.com

  - name: community.crypto
    version: ">2.20.0,<2.22.0"
    source: https://galaxy.ansible.com
