---
- name: Check certificate_dir variable
  ansible.builtin.assert:
    fail_msg: >
      Variable `certificate_dir` must be defined.
    that:
      - certificate_dir is defined

- name: Stat certificate_dir
  local_action:
    module: ansible.builtin.stat
    path: "{{ certificate_dir }}"
  register: certificate_dir_result

- name: "Debug certificate_dir_result"
  ansible.builtin.debug:
    var: certificate_dir_result

- name: Check that certificate_dir exists
  ansible.builtin.assert:
    fail_msg: >
      Directory {{ certificate_dir }} does not exist.
    that:
      - certificate_dir_result.stat.exists
