---
- name: Restart dovecot
  ansible.builtin.service:
    name: "{{ dovecot_service }}"
    state: restarted

- name: Validate dovecot.conf
  ansible.builtin.command: "dovecot -n"
  no_changed_when: true
