---
- name: Converge
  hosts: all
  vars:
    certificate_self_signed: true
    dovecot_certificate_dir: certs
    dovecot_user_list:
      - username: test@example.com
        password: supersecrettypico

  tasks:
    - name: Create certificate directory
      ansible.builtin.raw: "mkdir -p {{ dovecot_certificate_dir }}"
      changed_when: false
      delegate_to: localhost
    - name: "Include sv0.dovecot"
      ansible.builtin.include_role:
        name: "sv0.dovecot"
