---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    # image: docker.io/pycontribs/centos:8
    image: ansible:latest
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: ansible
