---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: debian11
    image: docker.io/slavik0/ci:debian11-latest
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: ansible
