---
- name: Prepare
  hosts: all
  vars:
    dovecot_certificate_dir: certs

  tasks:
    - name: Debug
      ansible.builtin.debug:
        # var: ansible_distribution_release
        var: ansible_distribution

    - name: Run apt-get update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

    - name: Install net-tools (required by testinfa)
      ansible.builtin.apt:
        name: net-tools

    - name: Create certificate directory
      raw: "mkdir -p {{ dovecot_certificate_dir }}"
      changed_when: false
      delegate_to: localhost
