---
- name: Prepare
  hosts: all
  vars:
    dovecot_certificate_dir: certs

  tasks:
    - name: Debug
      ansible.builtin.debug:
        var: ansible_distribution

    - name: Run apt-get update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

    - name: Install net-tools (required by testinfa)
      ansible.builtin.apt:
        name: net-tools

    - name: Generate a Self Signed OpenSSL certificate
      shell: |
        openssl genrsa -out "/etc/ssl/private/{{ inventory_hostname }}.key" 4096
        openssl req -new -x509 -key "/etc/ssl/private/{{ inventory_hostname }}.key" \
          -out "/etc/ssl/{{ inventory_hostname }}.crt" -days 365 \
          -subj "/C=US/ST=Example/L=Example/O=Dis/CN={{ inventory_hostname }}"
